//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyLayoutAutoSwitch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyLayoutAutoSwitch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Layout Auto Switch.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other web pages.
        /// </summary>
        internal static string DefaultPageRule {
            get {
                return ResourceManager.GetString("DefaultPageRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For web pages which do not match any other rule:.
        /// </summary>
        internal static string DefaultPageRuleDescription {
            get {
                return ResourceManager.GetString("DefaultPageRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Browser controls.
        /// </summary>
        internal static string DefaultUIElementRule {
            get {
                return ResourceManager.GetString("DefaultUIElementRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a Browser element that does not match any other rule has the focus:.
        /// </summary>
        internal static string DefaultUIElementRuleDescription {
            get {
                return ResourceManager.GetString("DefaultUIElementRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} web pages.
        /// </summary>
        internal static string DomainRule {
            get {
                return ResourceManager.GetString("DomainRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For web pages where the domain name ends in:.
        /// </summary>
        internal static string DomainRuleDescription {
            get {
                return ResourceManager.GetString("DomainRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match web page setting.
        /// </summary>
        internal static string FindInPageMatchWebPage {
            get {
                return ResourceManager.GetString("FindInPageMatchWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Page.
        /// </summary>
        internal static string FindInPageRule {
            get {
                return ResourceManager.GetString("FindInPageRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Find in Page has the focus:.
        /// </summary>
        internal static string FindInPageRuleDescription {
            get {
                return ResourceManager.GetString("FindInPageRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure....
        /// </summary>
        internal static string IconMenuConfigure {
            get {
                return ResourceManager.GetString("IconMenuConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string IconMenuExit {
            get {
                return ResourceManager.GetString("IconMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Previously Visited.
        /// </summary>
        internal static string IconMenuResetPreviouslyVisited {
            get {
                return ResourceManager.GetString("IconMenuResetPreviouslyVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LanguageBar {
            get {
                object obj = ResourceManager.GetObject("LanguageBar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string LanguageDisplayFormat {
            get {
                return ResourceManager.GetString("LanguageDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change.
        /// </summary>
        internal static string LanguageDoNotChange {
            get {
                return ResourceManager.GetString("LanguageDoNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Bar.
        /// </summary>
        internal static string LocationBarRule {
            get {
                return ResourceManager.GetString("LocationBarRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the Location Bar has the focus:.
        /// </summary>
        internal static string LocationBarRuleDescription {
            get {
                return ResourceManager.GetString("LocationBarRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a web page has previously been visited, and a different keyboard layout was manually switched to for it:.
        /// </summary>
        internal static string PrevioulsyVisitedPageRuleDescription {
            get {
                return ResourceManager.GetString("PrevioulsyVisitedPageRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore last used keyboard layout.
        /// </summary>
        internal static string PreviouslyVisitedPageRestoreLayout {
            get {
                return ResourceManager.GetString("PreviouslyVisitedPageRestoreLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore last used keyboard layout for site.
        /// </summary>
        internal static string PreviouslyVisitedPageRestoreLayoutForSite {
            get {
                return ResourceManager.GetString("PreviouslyVisitedPageRestoreLayoutForSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously visited web pages.
        /// </summary>
        internal static string PreviouslyVisitedPageRule {
            get {
                return ResourceManager.GetString("PreviouslyVisitedPageRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously visited page.
        /// </summary>
        internal static string PreviouslyVisitedPageRuleNamePage {
            get {
                return ResourceManager.GetString("PreviouslyVisitedPageRuleNamePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously visited site: {0}.
        /// </summary>
        internal static string PreviouslyVisitedPageRuleNameSite {
            get {
                return ResourceManager.GetString("PreviouslyVisitedPageRuleNameSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save rules to {0}:
        ///
        ///{1}.
        /// </summary>
        internal static string SaveRulesErrorMessage {
            get {
                return ResourceManager.GetString("SaveRulesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Bar.
        /// </summary>
        internal static string SearchBarRule {
            get {
                return ResourceManager.GetString("SearchBarRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the Search Bar has the focus:.
        /// </summary>
        internal static string SearchBarRuleDescription {
            get {
                return ResourceManager.GetString("SearchBarRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched to &apos;{0}&apos; by rule: {1}.
        /// </summary>
        internal static string SwitchTooltip {
            get {
                return ResourceManager.GetString("SwitchTooltip", resourceCulture);
            }
        }
    }
}
